//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maternity.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baby
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baby()
        {
            this.Baby_Doctor = new HashSet<Baby_Doctor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime BirthDate { get; set; }
        public decimal Height { get; set; }
        public int MotherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baby_Doctor> Baby_Doctor { get; set; }
        public virtual Mother Mother { get; set; }
    }
}
